config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#home'

  get 'search' => 'static_pages#search'

  resources :brands do
    resources :products do
        resources :ingredients    
    end
  end

end

app/models/brand.rb
class Brand < ActiveRecord::Base
	
	belongs_to :owner, :class_name => "User", :foreign_key => :user_id


	has_many :products
	belongs_to :user

	validates :brand_cname, :presence => true
	validates :brand_name, :presence => true
	#validates :user_id, :presence => true

	def editable_by?(user)
    	user && user == owner
	end
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
	belongs_to :product
	belongs_to :user

	validates :ingredient_cname, :presence => true
	validates :ingredient_name, :presence => true
end

app/models/product.rb
class Product < ActiveRecord::Base
	
	belongs_to :brand
	has_many :ingredients
	belongs_to :type
	belongs_to :user
	#has_and_belongs_to_many :types


	validates :product_cname, :presence => true
	validates :product_name, :presence => true
	validates :type_id, :presence => true
end

app/models/type.rb
class Type < ActiveRecord::Base
	has_many :products
	#has_and_belongs_to_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :brands
  has_many :products
  has_many :ingredients

 # extend OmniauthCallbacks


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def login_required
  	if current_user.blank?
  		respond_to do |format|
  			format.html {
  				authenticate_user!
  			}
  			format.js{
  				render :partial => "common/not_logined"
  			}
  			format.all {
  				head(:unauthorized)
  			}
  		end
  	end
  end


protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:user_name, :email, :password,:password_confirmation)} 
  end



end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

before_action :login_required, :only => [:new, :create, :edit,:update,:destroy]
before_action :brand_setup, :only => [:show, :edit, :update, :destroy]

def index
	@brands = Brand.all
end

def new
	@brand = Brand.new
end

def create
	#@brand = Brand.new(brand_params)
	@brand = Brand.new(brand_params)
	@brand.save

	if @brand.save
    	flash[:success] = "品牌新增成功！"
      redirect_to brands_path
    	#debugger
      # Handle a successful save.
    else
      flash.now[:danger] = "品牌新增失敗！"
      #redirect_to new_brand_path
      render :new
    end
end

#In your controller, use flash when you're redirecting and flash.now when rendering.


def show

	#@brand = Brand.find(params[:id])
	@products = @brand.products
	@product_joined = @products.select("products.id, products.brand_id, products.product_name, products.product_cname, products.type_id, types.type_name, types.type_cname").joins('LEFT OUTER JOIN types ON types.id = products.type_id')
	#@product_joined = Product.select("products.*, types.*").joins('LEFT OUTER JOIN types ON types.id = products.type_id')
	#@type = Type.find(params[@product_type])
	debugger
end

def edit
	#@brand = Brand.find(params[:id])

	# if @group.user != current_user 
	# 	flash[:warning] = "No Permission" 
	# redirec_to root_path
	# end
end

def update
	#@brand = Brand.find(params[:id])
		
	if @brand.update(brand_params)
		redirect_to brands_path(@brand)
	else
		render :edit
	end
end

def destroy
	#@brand = Brand.find(params[:id])
	@delete_msg = "確認要刪除" + @brand.brand_cname + "?"
	@brand.destroy
	redirect_to brands_path
end


private

def brand_params
	params.require(:brand).permit(:brand_name, :brand_cname, :user_id)
end

def brand_setup
	@brand = Brand.find(params[:id])
end



end #end of brands controller

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	def new
		@brand = Brand.find(params[:brand_id])
		@product = Product.find(params[:product_id])
		@ingredient = @product.ingredients.build
	end

	def show
		@brand = Brand.find(params[:brand_id])	
		@product = Product.find(params[:product_id])
		@ingredient = @product.ingredients.find(params[:id])
	end

	def create
		@brand = Brand.find(params[:brand_id])	
		@product = Product.find(params[:product_id])
		@ingredient = @product.ingredients.new(ingredient_params)

		if @ingredient.save
			flash[:success] = "成分新增成功！"
	 		redirect_to brand_product_path(@brand, @product)
	 	else	
	 		flash.now[:danger] = "成分新增失敗！"
	 		render :new
	 	end
	end

	def edit
		@brand = Brand.find(params[:brand_id])	
		@product = Product.find(params[:product_id])
		@ingredient = @product.ingredients.find(params[:id])
	end

	def update
		@brand = Brand.find(params[:brand_id])
		@product = Product.find(params[:product_id])
		@ingredient = @product.ingredients.find(params[:id])

		if @ingredient.update(ingredient_params)
	       redirect_to brand_product_path(@brand, @product)
		else
		   render :edit
		end
	end

	def destroy
		@brand = Brand.find(params[:brand_id])
		@product = Product.find(params[:product_id])
		@ingredient = @product.ingredients.find(params[:id])

		@ingredient.destroy
		#redirect_to brand_product_path(@product)
		redirect_to brand_product_path(@brand, @product)
	end

private
	def ingredient_params
		params.require(:ingredient).permit(:ingredient_name, :ingredient_cname, :cas_number)
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

def new
	@brand = Brand.find(params[:brand_id])
	@product = @brand.products.build
	@type = Type.all
	#@product = @brand.products.new(product_params)
	end

def show
	@brand = Brand.find(params[:brand_id])
	@product = @brand.products.find(params[:id])
	@type = Type.find(@product.type_id)
	@ingredients = @product.ingredients
	#@product_joined = Product.select("products.id, products.brand_id, products.product_name, products.product_cname, products.type_id, types.type_name, types.type_cname").joins('LEFT OUTER JOIN types ON types.id = products.type_id')
end

def create
	@brand = Brand.find(params[:brand_id])
	@product = @brand.products.new(product_params)
	@type = Type.all

	if @product.save
    	flash[:success] = "產品新增成功！"
      redirect_to brand_path(@brand)
    	#debugger
      # Handle a successful save.
    else
      flash.now[:danger] = "產品新增失敗！"
	  #redirect_to new_brand_product_path
	  render :new
    end
end

def edit
	@brand = Brand.find(params[:brand_id])
	@product= @brand.products.find(params[:id])
	@type = Type.all

end

def update
	@brand = Brand.find(params[:brand_id])
	@product = @brand.products.find(params[:id])

	if @product.update(product_params)
	    #redirect_to brand_product_path(@brand, @product)
	    redirect_to brand_path(@brand)
	else
		render :edit
	end
 end

 def destroy
 	@brand = Brand.find(params[:brand_id])
	@product= @brand.products.find(params[:id])

	@product.destroy
	redirect_to brand_path(@brand)
 end

private

def product_params
	params.require(:product).permit(:brand_id, :product_name, :product_cname, :type_id)
end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

	def search

		@product_branded = Product.joins(:type, :brand)
		@product_joined = Product.select("products.id, products.brand_id, products.product_name, products.product_cname, products.type_id, types.type_name, types.type_cname, brands.brand_name, brands.brand_cname").joins('OUTER JOIN types ON types.id = products.type_id OUTER JOIN brands ON brands.id = products.brand_id')
		#@brand = Brand.find(@product_branded.brand_id)
		#@type = Type.find(@products_branded.type_id)
		#@product_branded = Product.select("brands.brand_cname, brands.brand_name, products.type").joins('LEFT OUTER JOIN types ON brands.id = products.brand_id')
		#@product_branded = Product.includes(:brand)
		#@product_branded = Product.select("brands.*").includes(:brand)
		#Client.where("orders_count = ?", params[:orders])

	end

	def help
	end

	def contact
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "食安資料庫"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>
      <ul>
      <% @brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<form role="form">
  <div class="form-group">

  <div class="form-group">
    <label><%= f.label :'品牌名(英):' %></label><br>
    <%= f.text_field :brand_name %>
  </div>
  <div class="form-group">
    <%= f.label :'品牌名(中):' %><br>
    <%= f.text_field :brand_cname %>
  </div>
  
  <div class="actions">
    <% if current_page?(:controller => 'brands', :action => 'new') %>
    <%= f.submit "新增", class: "btn btn-primary" %>
    <% else %>
    <%= f.submit "編輯", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

  </div>
</form>

app/views/brands/_list.html.erb
<h3><b>產品列表</b></h3>
<div>	
	<table class="table table-hover table-bordered">

		<tbody>
			  <tr>

				<th><h4>品牌ID</h4></th>
				<th><h4>產品ID</h4></th>
				<th><h4>產品類別</h4></th>
				<th><h4>產品名(英文)</h4></th>
				<th><h4>品名(中文)</h4></th>
				<th colspan="3"><%= link_to '新增產品', new_brand_product_path(@brand), class: "btn btn-primary" if current_user %></th>
  			  </tr>


			<% @product_joined.each do |product| %>
			<tr>
				<td> <%= product.brand_id %> </td>
				<td> <%= product.id %> </td>
 				<td> <%= product.type_cname %> </td> 
				<td> <%= product.product_name %> </td>
				<td> <%= product.product_cname %> </td>

				<td> <%= link_to("查詢", brand_product_path(product.brand, product))%></td>
				<td> 
					<%# if current_user && @brand.editable_by?(current_user) %>
					<% if !current_user.blank?  %>
					<%= link_to("編輯", edit_brand_product_path(product.brand, product))%>
					<% end %>
				</td>
 				<td>
 					<%# if current_user && @brand.editable_by?(current_user) %>
 					<% if !current_user.blank? %>
 					<%= link_to("刪除", brand_product_path(product.brand, product), :method => :delete, :confirm => "Are you sure?" ) %> 
 					<% end %>
 				</td>
			</tr>
			<% end %>


		</tbody>
	</table>
</div>

app/views/brands/edit.html.erb
<h1>編輯品牌</h1>

<%= render 'form' %>

<%= link_to '查詢', @brand %> |
<%= link_to '回首頁', brands_path %>

app/views/brands/index.html.erb
<h1><b>品牌列表</b></h1>

<table class="table table-hover table-bordered">
  <tr>
    <th><h4>品牌ID</h4></th>

    <th><h4>品牌名(英文)</h4></th>

    <th><h4>品牌名(中文)</h4></th>

    <th colspan="3"><%= link_to '新增品牌', new_brand_path, class: "btn btn-primary"%></th>

    </tr>

  <% @brands.each do |brand| %>
    <tr>
      <td><%= brand.id %></td>
      <td><%= brand.brand_name %></td>
      <td><%= brand.brand_cname %></td>
      <td><%= link_to '查詢', brand_path(brand) %></td>
      <td>
        <% if !current_user.blank? %>
        <%= link_to '編輯', edit_brand_path(brand) %>
        <% end %>
      </td>
      <td>
        <% if !current_user.blank? %>
        <%= link_to '刪除', brand_path(brand), method: :delete, data: { confirm: "Are you sure?" } %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/brands/new.html.erb
<h1>新增品牌</h1>

<%= render 'form' %>

<%= link_to '回首頁', brands_path %>

app/views/brands/show.html.erb
<h1><b><%= @brand.brand_cname %> 品牌細節</b></h1>
<div class="span12">
  <table class="table table-striped table-bordered">
  	  <tr>
	    <th><h4>品牌 ID:</h4></th>   <td><h4><%= @brand.id %></h4></td>
	  </tr>
	  <tr>
	    <th><h4>品牌名(英):</h4></th>   <td><h4><%= @brand.brand_name %></h4></td>
	  </tr>
	  <tr>
	    <th><h4>品牌名(中):</h4></th>    <td><h4><%= @brand.brand_cname %></h4></td>
	  </tr>

  
  </table>

<br>
<%= render 'list' %>
<br>

<%= link_to '回品牌列表', brands_path %>

app/views/ingredients/_form.html.erb
<%= form_for [@brand, @product, @ingredient] do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this brand from being saved:</h2>
      <ul>
      <% @ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<form role="form">
  <div class="form-group">
  
  <div class="form-group">
    <label><%= f.label :'成分名(英):' %></label><br>
    <%= f.text_field :ingredient_name %>
  </div>
  <div class="form-group">
    <label><%= f.label :'成分名(中):' %></label><br>
    <%= f.text_field :ingredient_cname %>
  </div>
  <div class="form-group">
    <%= f.label :'CAS 編號:'.upcase %><br>
    <%= f.text_field :cas_number %>
    <br>
    <%= link_to "CAS標號是什麼？", "http://zh.wikipedia.org/wiki/CAS%E5%8F%B7", :target => "_blank"%>
    <br>
    <%= link_to "CAS編號查詢網頁", "http://www.molbase.com/en/index.html", :target => "_blank"%>
  </div>

  <div class="actions">
    <% if current_page?(:controller => 'ingredients', :action => 'new') %>
    <%= f.submit "新增", class: "btn btn-primary" %>
    <% else %>
    <%= f.submit "編輯", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

  </div>
</form>

app/views/ingredients/edit.html.erb
<h1>編輯成分</h1>

<%= render 'form' %>

<%= link_to("返回產品", brand_product_path(@brand, @product))%>

app/views/ingredients/new.html.erb
<h1>新增成分</h1>

<%= render 'form' %>

<%= link_to("返回產品", brand_product_path(@brand, @product))%>

app/views/ingredients/show.html.erb
<h1><b><%= @ingredient.ingredient_cname %> 成分細節</b></h1>
<div class="span12">
  <table class="table table-striped table-bordered">
	  <tr>
	    <th><h4>成分名(英):</h4></th>   <td><h4><%= @ingredient.ingredient_name %></h4></td>
	  </tr>
	  <tr>
	    <th><h4>成分名(中):</h4></th>    <td><h4><%= @ingredient.ingredient_cname %></h4></td>
	  </tr>
	  <tr>
	    <th><h4>CAS編碼:</h4></th>    <td><h4><%= @ingredient.cas_number %></h4></td>
	  </tr>
  </table>

<%= link_to '回產品列表', brand_product_path(@brand, @product) %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    © 2014食安資料庫系統 by Eugene Chang
  </small>
  <nav>
    <ul>
      <li><%= link_to "關於",   '#' %></li>
      <li><%= link_to "連略我們", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "食安資料庫", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">

        <li><%= link_to "搜尋產品",  search_path  %></li>
        <li><%#= link_to "問題",   '#' %></li>
<!--         <%# if user_signed_in? %>
       <li>Logged in as <%#= current_user.email %></li> 
        <li><%#= link_to "登出", destroy_user_session_path, :method => :delete %></li>
        <%# end %> -->

        <% #if user_signed_in? %>
          <li><%#= link_to edit_user_registration_path do %>
             <%#= current_user.email %></li>
          <% #end %>
          <li><%#= link_to "登出", destroy_user_session_path, :method => :delete %></li>
            
        <% #end %> 


        <% if user_signed_in? %>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.email %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "設定", edit_user_registration_path  %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "登出", destroy_user_session_path, :method => :delete %>
              </li>
            </ul>
          </li>

        <% else %>
          <li><%= link_to "登入", new_user_session_path %></li>
        <% end %>

      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  	
  	<%= render 'layouts/header' %>
    
    <div class="container">
    <% #flash.each do |message_type, message| %>
      <div class="alert alert-<%#= message_type %>"><%#= message %></div>
    <% #end %>
    <% if notice %>
  		<p class="alert alert-success"><%= notice %></p>
	<% end %>
	<% if alert %>
  		<p class="alert alert-danger"><%= alert %></p>
	<% end %>
    
    <%= yield %>
    
    <%= render 'layouts/footer' %>
    <br>
    <%= params.inspect %>

    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for [@brand, @product] do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this brand from being saved:</h2>
      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<form role="form">
  <div class="form-group">
  
  <div class="form-group">
    <label><%= f.label :'產品類別:' %></label><br>
    <% if current_page?(:controller => 'products', :action => 'new') %>
      <%= f.collection_select(:type_id, @type, :id, :type_cname, :include_blank => "請選擇...") %>
    <% else %>
      <%= f.collection_select(:type_id, @type, :id, :type_cname, :selected => @product.type_id.to_i) %>
    <% end %>
  </div>





  <div class="form-group">
    <label><%= f.label :'產品名(英):' %></label><br>
    <%= f.text_field :product_name %>
  </div>
  <div class="form-group">
    <%= f.label :'產品名(中):' %><br>
    <%= f.text_field :product_cname %>
  </div>
  <div class="actions">
    <% if current_page?(:controller => 'products', :action => 'new') %>
    <%= f.submit "新增", class: "btn btn-primary" %>
    <% else %>
    <%= f.submit "編輯", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

  </div>
</form>

app/views/products/_list.html.erb
<h3><b>成分列表</b></h3>
	
	<table class="table table-hover table-bordered">

		<tbody>
			  <tr>
			    <th><h4>成分ID</h4></th>

    			<th><h4>成分名(英)</h4></th>

    			<th><h4>成分名(中)</h4></th>

    			<th><h4>CAS編號</h4></th>

    			<th colspan="3"><%= link_to '新增成分', new_brand_product_ingredient_path(@brand, @product, @ingredient), class: "btn btn-primary" %></th>
  			  </tr>

			<% @ingredients.each do |ingredient| %>
			<tr>
				<td> <%= ingredient.id %> </td>
				<td> <%= ingredient.ingredient_name %> </td>
				<td> <%= ingredient.ingredient_cname %> </td>
				<td> <%= ingredient.cas_number %> </td>

				<td> <%= link_to("查詢", brand_product_ingredient_path(@brand.id, ingredient.product_id, ingredient))%> </td>
				<td> <%= link_to("編輯", edit_brand_product_ingredient_path(@brand.id, ingredient.product_id, ingredient))%> </td>
 				<td> <%= link_to("刪除", brand_product_ingredient_path(@brand.id, ingredient.product_id, ingredient), :method => :delete, :confirm => "Are you sure?" ) %> </td>
			</tr>
			<% end %>

		</tbody>
	</table>
</div>

app/views/products/edit.html.erb
<h1>編輯產品</h1>

<%= render 'form' %>

<%= link_to '返回產品', brand_path(@brand) %>

app/views/products/new.html.erb
<h1>新增 <b><%= @brand.brand_cname %></b> 產品</h1>

<%= render 'form' %>

<%= link_to '返回產品', brand_path(@brand) %>

app/views/products/show.html.erb
<h1><b><%= @product.product_cname %> 產品細節</b></h1>
<div class="span12">
  <table class="table table-striped table-bordered">
	  <tr>
	    <th><h4>品牌名(英):</h4></th>   <td><h4><%= @brand.brand_name %></h4></td>
	  </tr>
	  <tr>
	    <th><h4>品牌名(中):</h4></th>    <td><h4><%= @brand.brand_cname %></h4></td>
	  </tr>
	  <tr>
	    <th><h4>產品類別:</h4></th>    <td><h4><%= @type.type_cname %></h4></td>
	  </tr>
	  <tr>
	    <th><h4>產品名(英):</h4></th>    <td><h4><%= @product.product_name %></h4></td>
	  </tr>
	  <tr>
	    <th><h4>產品名(中):</h4></th>    <td><h4><%= @product.product_cname %></h4></td>
	  </tr>
  </table>

<br>
<%= render 'list' %>
<br>

<%= link_to '回品牌列表', brand_path(@brand) %>

app/views/shared/_error_messages.html.erb
<% if @brand.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@brand.errors.count, "error") %>.
    </div>
    <ul>
    <% @brand.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/_results.html.erb
	<table class="table table-hover table-bordered">

		<tbody>
			  <tr>

<!-- 				<th><h4>品牌名(中)</h4></th>
				<th><h4>品牌名(英)</h4></th>
				<th><h4>產品類別</h4></th> -->
				<th><h4>品牌名(中)</h4></th>
				<th><h4>類別(中)</h4></th>
				<th><h4>產品ID</h4></th>
				<th><h4>產品名(英)</h4></th>
				<th><h4>產品名(中)</h4></th>
				<th colspan="3"></th>
  			  </tr>


			<% @product_branded.each do |product| %>
			<tr>
				<td> <%= product.brand_id %> </td> 
				<td> <%= product.type_id %> </td> 	
 				<td> <%= product.id %> </td> 
				<td> <%= product.product_name %> </td>
				<td> <%= product.product_cname %> </td>

				<td> <%= link_to("查詢", brand_product_path(product.brand, product))%></td>
				<td> <%= link_to("編輯", edit_brand_product_path(product.brand, product))%></td>
 				<td> <%= link_to("刪除", brand_product_path(product.brand, product), :method => :delete, :confirm => "Are you sure?" ) %> </td>
			</tr>
			<% end %>


		</tbody>
	</table>

app/views/static_pages/_search_form.html.erb
<% form_for search_path, :method => 'get' do %>
<form role="form">
	<div class="form-group">
		<%= text_field_tag :search, params[:search] %>
	</div>
	<div class="form-group">
		<%= submit_tag "Search", :name => nil %>

<% end %>
	</div>
</form>

app/views/static_pages/help.html.erb
<%= params.inspect %>
<%= render 'brands/list' %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1><b>食安資料庫</b></h1>
  <br>
  <h3>這是針對搜集市面上販售的食品, 日用品, 以及化妝品成分所建立的系統</h3>
  <br>
  <% if user_signed_in? %>
  	<%= link_to "進入", brands_path, class: "btn btn-lg btn-primary" %>
  <% else %>
  	<%= link_to '登入', new_user_session_path, class: "btn btn-lg btn-primary" %>
  	<%= link_to '訪客參觀', brands_path, class: "btn btn-lg btn-primary" %>
  <% end %>

</div>

app/views/static_pages/search.html.erb
<h1><b>搜尋結果</b></h1>

<%= render 'results'%>